apiVersion: v1
kind: Service
metadata:
  name: verbs
  labels:
    app: verbs
spec:
  ports:
    - port: 8080
      targetPort: 8080
  clusterIP: 10.43.0.20
  selector:
    app: verbs
  type: ClusterIP