apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels:
    app: aggregator
    service: aggregator
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: aggregator